/*
 * MODULE 8: LLVM IR GENERATION (Implementation)
 * Mini-Compiler Project - CS-346 Compiler Construction
 *
 * Generates LLVM IR from optimized TAC code.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "llvm_generator.h"

/* Track allocated variables */
typedef struct {
    char name[MAX_OPERAND_LEN];
    char llvm_name[MAX_OPERAND_LEN];
    DataType type;
    int is_alloca;
} LLVMVar;

typedef struct {
    LLVMVar vars[1000];
    int count;
    FILE *out;
    int temp_count;
    int label_count;
    char current_func[MAX_TOKEN_LEN];
} LLVMContext;

/* Get LLVM type string */
const char* get_llvm_type(DataType type) {
    switch (type) {
        case TYPE_INT:   return "i32";
        case TYPE_FLOAT: return "double";
        case TYPE_CHAR:  return "i8";
        case TYPE_BOOL:  return "i1";
        case TYPE_VOID:  return "void";
        default:         return "i32";
    }
}

/* Check if string is numeric */
static int is_numeric(const char *s) {
    if (!s || !*s) return 0;
    if (*s == '-') s++;
    int has_dot = 0;
    while (*s) {
        if (*s == '.') {
            if (has_dot) return 0;
            has_dot = 1;
        } else if (!isdigit(*s)) {
            return 0;
        }
        s++;
    }
    return 1;
}

/* Get LLVM register name for operand */
static const char* get_operand(LLVMContext *ctx, const char *op, char *buf) {
    if (!op || !op[0]) {
        strcpy(buf, "0");
        return buf;
    }

    if (is_numeric(op)) {
        strcpy(buf, op);
        return buf;
    }

    /* Temporary or variable */
    if (op[0] == 't' && isdigit(op[1])) {
        snprintf(buf, MAX_OPERAND_LEN, "%%t%s", op + 1);
    } else {
        snprintf(buf, MAX_OPERAND_LEN, "%%%s", op);
    }
    return buf;
}

/* Emit LLVM IR prologue */
static void emit_prologue(LLVMContext *ctx) {
    fprintf(ctx->out, "; LLVM IR generated by Mini-Compiler\n");
    fprintf(ctx->out, "; CS-346 Compiler Construction Project\n\n");

    /* Declare external functions */
    fprintf(ctx->out, "; External function declarations\n");
    fprintf(ctx->out, "declare i32 @printf(i8*, ...)\n");
    fprintf(ctx->out, "declare i32 @scanf(i8*, ...)\n");
    fprintf(ctx->out, "declare double @pow(double, double)\n");
    fprintf(ctx->out, "declare double @log(double)\n");
    fprintf(ctx->out, "declare double @exp(double)\n");
    fprintf(ctx->out, "declare double @sqrt(double)\n");
    fprintf(ctx->out, "declare double @sin(double)\n");
    fprintf(ctx->out, "declare double @cos(double)\n");
    fprintf(ctx->out, "declare double @tan(double)\n");
    fprintf(ctx->out, "\n");

    /* String constants for printf */
    fprintf(ctx->out, "; String constants\n");
    fprintf(ctx->out, "@.str.int = private constant [4 x i8] c\"%%d\\0A\\00\"\n");
    fprintf(ctx->out, "@.str.float = private constant [4 x i8] c\"%%f\\0A\\00\"\n");
    fprintf(ctx->out, "\n");
}

/* Generate LLVM IR for TAC instruction */
static void emit_instruction(LLVMContext *ctx, TACInstruction *instr) {
    char op1[MAX_OPERAND_LEN], op2[MAX_OPERAND_LEN], res[MAX_OPERAND_LEN];

    if (instr->is_dead) {
        fprintf(ctx->out, "  ; DEAD CODE: %s = %s %s %s\n",
                instr->result, instr->arg1,
                tac_op_to_string(instr->op), instr->arg2);
        return;
    }

    get_operand(ctx, instr->arg1, op1);
    get_operand(ctx, instr->arg2, op2);
    get_operand(ctx, instr->result, res);

    switch (instr->op) {
        case OP_ADD:
            if (strchr(op1, '.') || strchr(op2, '.')) {
                fprintf(ctx->out, "  %s = fadd double %s, %s\n", res, op1, op2);
            } else {
                fprintf(ctx->out, "  %s = add i32 %s, %s\n", res, op1, op2);
            }
            break;

        case OP_SUB:
            if (strchr(op1, '.') || strchr(op2, '.')) {
                fprintf(ctx->out, "  %s = fsub double %s, %s\n", res, op1, op2);
            } else {
                fprintf(ctx->out, "  %s = sub i32 %s, %s\n", res, op1, op2);
            }
            break;

        case OP_MUL:
            if (strchr(op1, '.') || strchr(op2, '.')) {
                fprintf(ctx->out, "  %s = fmul double %s, %s\n", res, op1, op2);
            } else {
                fprintf(ctx->out, "  %s = mul i32 %s, %s\n", res, op1, op2);
            }
            break;

        case OP_DIV:
            if (strchr(op1, '.') || strchr(op2, '.')) {
                fprintf(ctx->out, "  %s = fdiv double %s, %s\n", res, op1, op2);
            } else {
                fprintf(ctx->out, "  %s = sdiv i32 %s, %s\n", res, op1, op2);
            }
            break;

        case OP_MOD:
            fprintf(ctx->out, "  %s = srem i32 %s, %s\n", res, op1, op2);
            break;

        case OP_ASSIGN:
        case OP_COPY:
            if (is_numeric(instr->arg1)) {
                if (strchr(instr->arg1, '.')) {
                    fprintf(ctx->out, "  %s = fadd double 0.0, %s\n", res, op1);
                } else {
                    fprintf(ctx->out, "  %s = add i32 0, %s\n", res, op1);
                }
            } else {
                fprintf(ctx->out, "  %s = add i32 0, %s  ; copy\n", res, op1);
            }
            break;

        case OP_UMINUS:
            if (strchr(op1, '.')) {
                fprintf(ctx->out, "  %s = fsub double 0.0, %s\n", res, op1);
            } else {
                fprintf(ctx->out, "  %s = sub i32 0, %s\n", res, op1);
            }
            break;

        case OP_LT:
            fprintf(ctx->out, "  %s = icmp slt i32 %s, %s\n", res, op1, op2);
            break;

        case OP_LE:
            fprintf(ctx->out, "  %s = icmp sle i32 %s, %s\n", res, op1, op2);
            break;

        case OP_GT:
            fprintf(ctx->out, "  %s = icmp sgt i32 %s, %s\n", res, op1, op2);
            break;

        case OP_GE:
            fprintf(ctx->out, "  %s = icmp sge i32 %s, %s\n", res, op1, op2);
            break;

        case OP_EQ:
            fprintf(ctx->out, "  %s = icmp eq i32 %s, %s\n", res, op1, op2);
            break;

        case OP_NE:
            fprintf(ctx->out, "  %s = icmp ne i32 %s, %s\n", res, op1, op2);
            break;

        case OP_AND:
            fprintf(ctx->out, "  %s = and i1 %s, %s\n", res, op1, op2);
            break;

        case OP_OR:
            fprintf(ctx->out, "  %s = or i1 %s, %s\n", res, op1, op2);
            break;

        case OP_NOT:
            fprintf(ctx->out, "  %s = xor i1 %s, true\n", res, op1);
            break;

        case OP_GOTO: {
            const char *lbl = instr->label[0] ? instr->label : instr->arg1;
            fprintf(ctx->out, "  br label %%%s\n", lbl);
            break;
        }

        case OP_IFGOTO: {
            const char *lbl = instr->label[0] ? instr->label : instr->arg2;
            char next_label[64];
            snprintf(next_label, sizeof(next_label), "cont_%d", ctx->label_count++);
            fprintf(ctx->out, "  br i1 %s, label %%%s, label %%%s\n",
                    op1, lbl, next_label);
            fprintf(ctx->out, "%s:\n", next_label);
            break;
        }

        case OP_IFFALSE: {
            const char *lbl = instr->label[0] ? instr->label : instr->arg2;
            char next_label[64];
            snprintf(next_label, sizeof(next_label), "cont_%d", ctx->label_count++);
            fprintf(ctx->out, "  br i1 %s, label %%%s, label %%%s\n",
                    op1, next_label, lbl);
            fprintf(ctx->out, "%s:\n", next_label);
            break;
        }

        case OP_PARAM:
            fprintf(ctx->out, "  ; param %s\n", op1);
            break;

        case OP_CALL:
            if (strcmp(instr->arg1, "printf") == 0 ||
                strcmp(instr->arg1, "print") == 0) {
                fprintf(ctx->out, "  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.str.int, i32 0, i32 0), i32 %s)\n", op1);
            } else if (strcmp(instr->arg1, "pow") == 0) {
                fprintf(ctx->out, "  %s = call double @pow(double %s, double %s)\n",
                        res, op1, op2);
            } else if (strcmp(instr->arg1, "log") == 0 ||
                       strcmp(instr->arg1, "exp") == 0 ||
                       strcmp(instr->arg1, "sqrt") == 0 ||
                       strcmp(instr->arg1, "sin") == 0 ||
                       strcmp(instr->arg1, "cos") == 0 ||
                       strcmp(instr->arg1, "tan") == 0) {
                fprintf(ctx->out, "  %s = call double @%s(double %s)\n",
                        res, instr->arg1, op1);
            } else {
                fprintf(ctx->out, "  %s = call i32 @%s()\n", res, instr->arg1);
            }
            break;

        case OP_RETURN:
            if (instr->arg1[0]) {
                if (strchr(op1, '.')) {
                    fprintf(ctx->out, "  ret double %s\n", op1);
                } else if (is_numeric(instr->arg1)) {
                    fprintf(ctx->out, "  ret i32 %s\n", instr->arg1);
                } else {
                    fprintf(ctx->out, "  ret i32 %s\n", op1);
                }
            } else {
                fprintf(ctx->out, "  ret void\n");
            }
            break;

        case OP_FUNC:
            /* Close previous function if any */
            if (ctx->current_func[0]) {
                fprintf(ctx->out, "}\n\n");
            }
            strcpy(ctx->current_func, instr->arg1);

            if (strcmp(instr->arg1, "main") == 0) {
                fprintf(ctx->out, "define i32 @main() {\n");
                fprintf(ctx->out, "entry:\n");
            } else {
                fprintf(ctx->out, "define i32 @%s() {\n", instr->arg1);
                fprintf(ctx->out, "entry:\n");
            }
            break;

        case OP_LABEL:
            fprintf(ctx->out, "%s:\n", instr->arg1);
            break;

        case OP_ARRAY_REF:
            fprintf(ctx->out, "  ; %s = %s[%s] (array access)\n",
                    res, op1, op2);
            break;

        case OP_ARRAY_ASSIGN:
            fprintf(ctx->out, "  ; %s[%s] = %s (array assign)\n",
                    res, op1, op2);
            break;

        case OP_NOP:
            fprintf(ctx->out, "  ; nop\n");
            break;

        default:
            fprintf(ctx->out, "  ; unknown instruction\n");
    }
}

/* Generate LLVM IR from TAC */
int generate_llvm_ir(TACCode *tac, SymbolTable *symbols, const char *output_file) {
    LLVMContext ctx;
    memset(&ctx, 0, sizeof(ctx));

    ctx.out = fopen(output_file, "w");
    if (!ctx.out) {
        fprintf(stderr, "Cannot open output file: %s\n", output_file);
        return -1;
    }

    printf("\n--- Generating LLVM IR ---\n");

    emit_prologue(&ctx);

    /* Check if there's a main function in TAC */
    int has_main = 0;
    for (int i = 0; i < tac->count; i++) {
        if (tac->instructions[i].op == OP_FUNC &&
            strcmp(tac->instructions[i].arg1, "main") == 0) {
            has_main = 1;
            break;
        }
    }

    /* If no main, wrap everything in main */
    if (!has_main) {
        fprintf(ctx.out, "define i32 @main() {\n");
        fprintf(ctx.out, "entry:\n");
        strcpy(ctx.current_func, "main");
    }

    /* Generate code for each instruction */
    for (int i = 0; i < tac->count; i++) {
        emit_instruction(&ctx, &tac->instructions[i]);
    }

    /* Close function and add return */
    if (ctx.current_func[0]) {
        if (strcmp(ctx.current_func, "main") == 0) {
            fprintf(ctx.out, "  ret i32 0\n");
        }
        fprintf(ctx.out, "}\n");
    }

    fclose(ctx.out);
    printf("LLVM IR written to: %s\n", output_file);

    return 0;
}

/* Generate with options */
int generate_llvm_ir_with_options(TACCode *tac, SymbolTable *symbols, LLVMOptions *opts) {
    return generate_llvm_ir(tac, symbols, opts->output_file);
}

/* Compile LLVM IR with Clang */
int compile_with_clang(const char *ll_file, const char *output_exe, int optimize) {
    char cmd[512];

    if (optimize) {
        snprintf(cmd, sizeof(cmd), "clang -O3 -o %s %s", output_exe, ll_file);
    } else {
        snprintf(cmd, sizeof(cmd), "clang -o %s %s", output_exe, ll_file);
    }

    printf("Compiling: %s\n", cmd);
    int result = system(cmd);

    if (result == 0) {
        printf("Compiled successfully: %s\n", output_exe);
    } else {
        printf("Compilation failed (Clang may not be installed)\n");
    }

    return result;
}

/* Print LLVM IR file */
void print_llvm_ir(const char *filename) {
    FILE *f = fopen(filename, "r");
    if (!f) {
        fprintf(stderr, "Cannot open file: %s\n", filename);
        return;
    }

    printf("\n========== LLVM IR (%s) ==========\n", filename);
    char line[1024];
    int line_num = 1;
    while (fgets(line, sizeof(line), f)) {
        printf("%3d: %s", line_num++, line);
    }
    printf("==========================================\n");

    fclose(f);
}

/* Standalone main for testing */
#ifdef LLVM_STANDALONE
int main(int argc, char *argv[]) {
    printf("=== MODULE 8: LLVM IR GENERATION ===\n\n");

    /* Create sample TAC */
    TACCode *tac = create_tac();

    /* Sample: main() { int x = 5; int y = 10; int z = x + y; return z; } */
    emit_tac(tac, OP_FUNC, NULL, "main", NULL);
    emit_tac(tac, OP_ASSIGN, "x", "5", NULL);
    emit_tac(tac, OP_ASSIGN, "y", "10", NULL);
    emit_tac(tac, OP_ADD, "t0", "x", "y");
    emit_tac(tac, OP_ASSIGN, "z", "t0", NULL);
    emit_tac(tac, OP_RETURN, NULL, "z", NULL);

    /* Print TAC */
    printf("--- Input TAC ---\n");
    print_tac(tac);

    /* Generate LLVM IR */
    const char *output = "output.ll";
    generate_llvm_ir(tac, NULL, output);

    /* Print generated IR */
    print_llvm_ir(output);

    /* Try to compile */
    compile_with_clang(output, "output.exe", 0);

    free_tac(tac);
    return 0;
}
#endif
