; LLVM IR generated by Mini-Compiler
; CS-346 Compiler Construction Project

; External function declarations
declare i32 @printf(i8*, ...)
declare i32 @scanf(i8*, ...)
declare double @pow(double, double)
declare double @log(double)
declare double @exp(double)
declare double @sqrt(double)
declare double @sin(double)
declare double @cos(double)
declare double @tan(double)

; String constants
@.str.int = private constant [4 x i8] c"%d\0A\00"
@.str.float = private constant [4 x i8] c"%f\0A\00"

define i32 @main() {
entry:
  ; DEAD CODE: t0 = 5 = 
  %a = add i32 0, 5
  ; DEAD CODE: t1 = 20 = 
  %b = add i32 0, 20
  ; DEAD CODE: t2 = 25 = 
  %c = add i32 0, 25
  %t3 = add i32 %x, 10
  %y = add i32 0, %t3  ; copy
  %t4 = mul i32 %x, 2
  %z = add i32 0, %t4  ; copy
  ; DEAD CODE: t5 = 25 = 
  %p = add i32 0, 25
  %t6 = add i32 0, 25
  %q = add i32 0, %t6  ; copy
  %t7 = add i32 25, %q
  %r = add i32 0, %t7  ; copy
  ret i32 0
}
